### ISSUE TITLE
Update Error 4.0.3 to 4.3.0

### ISSUE THREAD

**Issue by williamliao** [LycheeOrg/Lychee#1015]
### Detailed description of the problem [REQUIRED]

I follow these steps

```sh
# download the lastest files
git pull
# update the dependencies
composer install --no-dev
# apply the database migration
php artisan migrate
```

after I run `php artisan migrate`

output a error 
```
In RouteServiceProvider.php line 66:
Class 'Illuminate\Support\Facades\RateLimiter' not found
```

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

```
In storage/logs/laravel.log
[2021-05-22 11:50:19] local.ERROR: Class 'Illuminate\Support\Facades\RateLimiter' not found {"exception":"[object] (Error(code: 0): Class 'Illuminate\\Support\\Facades\\RateLimiter' not found at /home/***/***.com/Lychee-Laravel/app/Providers/RouteServiceProvider.php:66)
[stacktrace]
#0 /home/***/***.com/Lychee-Laravel/app/Providers/RouteServiceProvider.php(38): App\\Providers\\RouteServiceProvider->configureRateLimiting()
#1 [internal function]: App\\Providers\\RouteServiceProvider->boot()
#2 /home/***/***.com/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array(Array, Array)
#3 /home/***/***.com/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /home/***/***.com/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#5 /home/***/***.com/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#6 /home/***/***.com/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#7 /home/***/***.com/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(867): Illuminate\\Container\\Container->call(Array)
#8 /home/***/***.com/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(850): Illuminate\\Foundation\\Application->bootProvider(Object(App\\Providers\\RouteServiceProvider))
#9 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(App\\Providers\\RouteServiceProvider), 22)
#10 /home/***/***.com/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): array_walk(Array, Object(Closure))
#11 /home/***/***.com/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#12 /home/***/***.com/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(230): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#13 /home/***/***.com/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#14 /home/***/***.com/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#15 /home/***/***.com/Lychee-Laravel/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 {main}
"} 
```

**Comment by ildyria** [comment]
edited for readability.

**Comment by nagmat84** [comment]
Did you run `optimize:clear` and `composer install` in that order after you pulled with git? I had a similar problem once after I migrated from a lower version and skipped some intermediate upgrade. It seems that sometimes the cached, optimzed PHP files sometimes refer to older or moved dependencies.

**Comment by williamliao** [comment]
Thanks, I clear the cache and It's work.
