### ISSUE TITLE
Fail updating from 4.8.1

### ISSUE THREAD

**Issue by RoiArthurB** [LycheeOrg/Lychee#1904]
### Detailed description of the problem [REQUIRED]
I tried to git update from 4.8.1 to new latest version on my raspberrypi but it keeps failing with log below...

### Steps to reproduce the issue

1. Connect by ssh to my rasp
2. Move to installed folder
3. Run this upgrading command `sudo -u www-data git checkout v4.9.3 && composer install --no-dev --prefer-dist; php artisan optimize --clever ; php artisan migrate --force`
4. See error*

```
sudo -u www-data git checkout v4.9.3 && composer install --no-dev --prefer-dist; php artisan optimize --clever ; php artisan migrate --force
Previous HEAD position was 774e85ab version 4.8.1 (#1842)
HEAD is now at 94f670ac Improve explain on db_logging (#1898)
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - laravel/framework is locked to version v10.13.5 and an update of this package was not requested.
    - laravel/framework v10.13.5 requires composer-runtime-api ^2.2 -> found composer-runtime-api[2.1.0] but it does not match the constraint.
  Problem 2
    - laravel/framework v10.13.5 requires composer-runtime-api ^2.2 -> found composer-runtime-api[2.1.0] but it does not match the constraint.
    - spatie/laravel-image-optimizer 1.7.1 requires laravel/framework ^8.0|^9.0|^10.0 -> satisfiable by laravel/framework[v10.13.5].
    - spatie/laravel-image-optimizer is locked to version 1.7.1 and an update of this package was not requested.

PHP Fatal error:  Uncaught RuntimeException: A facade root has not been set. in /var/www/html/Lychee-v4/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:350
Stack trace:
#0 /var/www/html/Lychee-v4/app/Exceptions/Handler.php(390): Illuminate\Support\Facades\Facade::__callStatic()
#1 /var/www/html/Lychee-v4/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(503): App\Exceptions\Handler->report()
#2 /var/www/html/Lychee-v4/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(202): Illuminate\Foundation\Console\Kernel->reportException()
#3 /var/www/html/Lychee-v4/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#4 {main}
  thrown in /var/www/html/Lychee-v4/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 350
PHP Fatal error:  Uncaught RuntimeException: A facade root has not been set. in /var/www/html/Lychee-v4/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:350
Stack trace:
#0 /var/www/html/Lychee-v4/app/Exceptions/Handler.php(390): Illuminate\Support\Facades\Facade::__callStatic()
#1 /var/www/html/Lychee-v4/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(503): App\Exceptions\Handler->report()
#2 /var/www/html/Lychee-v4/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(202): Illuminate\Foundation\Console\Kernel->reportException()
#3 /var/www/html/Lychee-v4/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#4 {main}
  thrown in /var/www/html/Lychee-v4/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 350
```

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

```
$ php artisan lychee:diagnostics
PHP Fatal error:  Uncaught RuntimeException: A facade root has not been set. in /var/www/html/Lychee-v4/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:350
Stack trace:
#0 /var/www/html/Lychee-v4/app/Exceptions/Handler.php(390): Illuminate\Support\Facades\Facade::__callStatic()
#1 /var/www/html/Lychee-v4/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(503): App\Exceptions\Handler->report()
#2 /var/www/html/Lychee-v4/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(202): Illuminate\Foundation\Console\Kernel->reportException()
#3 /var/www/html/Lychee-v4/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#4 {main}
  thrown in /var/www/html/Lychee-v4/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 350
```

Here's my system info from 4.8.1 :

```

    System Information
    --------------
    Lychee Version (git):                    ?? (774e85a) -- Could not compare.
    DB Version:                              4.8.1
    
    composer install:                        --no-dev
    APP_ENV:                                 production
    APP_DEBUG:                               false
    
    System:                                  Linux
    PHP Version:                             8.1.20
    PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                                Europe/Paris
    Max uploaded file size:                  500M
    Max post size:                           500M
    Max execution time:                      200
    MySQL Version:                           10.5.19-MariaDB-0+deb11u2
    
    exec() Available:                        yes
    Imagick Available:                       1
    Imagick Enabled:                         1
    Imagick Version:                         1691
    GD Version:                              2.3.3
    Number of foreign key:                   11 found.
```

### Browser and system

Firefox / Chromium-based - Linux

**Comment by ildyria** [comment]
I am not able to reproduce locally. 

Even by doing :
```sh
git clone git@github.com:LycheeOrg/Lychee Lychee-4.8.1
cd Lychee-4.8.1
git checkout v4.8.1
composer install --no-dev --prefer-dist
php artisan migrate --force
git checkout v4.9.3
composer install --no-dev --prefer-dist
php artisan migrate --force
```

All the command pass. 

One way to fix your corrupt state would be to recreate another Lychee clone from latest master, do the composer install, move the upload folder, change the .env and apply the migration.

You should not be able to lose data, but I do agree that your error is very weird.
My intuition would tell me it is something related to the platform, but that does not really make sense.

**Comment by RoiArthurB** [comment]
Late update on this issue, but I only had time to work on it now.

The issue was really stupid, but it's because my composer was too old for used modules... Can found similar and fix here : https://stackoverflow.com/questions/75491621/laravel-frameworkv10-0-0-v10-0-3-require-composer-runtime-api-2-2-fo

The issue been solved after updating composer like this : 
```
$ composer clearcache
Cache directory does not exist (cache-vcs-dir): 
Clearing cache (cache-repo-dir): /home/pi/.cache/composer/repo
Clearing cache (cache-files-dir): /home/pi/.cache/composer/files
Clearing cache (cache-dir): /home/pi/.cache/composer
All caches cleared.

$ composer selfupdate
Upgrading to version 2.6.3 (stable channel).
   
Use composer self-update --rollback to return to version 2.1.12
```

This worked well, I moved to latest v4.12.0, composer install, migration and it's all working fine. Thanks everyone for this great project :hugs:
