### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by droplinxuser** [LycheeOrg/Lychee#2092]
I got this error when doing an update today:

```
# sudo -u www-data npm run build

> build
> vite build

file:///var/www/site.com/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

**Comment by ildyria** [comment]
Did you do:
```
npm install
```
**Are you using node 18 or better 20**?

**Comment by droplinxuser** [comment]
I'm using nodejs -v
version 12.22.9

Latest version from Ubuntu 22.04 repository.

Yes I did run npm install first.

**Comment by droplinxuser** [comment]
```
git pull 
composer install --no-dev
php artisan migrate
npm install
```

All the above commands run fine.
Only one issue happens when I run:
`npm run build`

**Comment by droplinxuser** [comment]
It works fine now after I upgraded to Node.js version 20.

**Comment by mjechow** [comment]
Thx. same for me, that saved my day! nodejs 21.5
