### ISSUE TITLE
Error 500 Class "Mockery" not found

### ISSUE THREAD

**Issue by makorus** [LycheeOrg/Lychee#2243]
### Detailed description of the problem [REQUIRED]
I tried to upgrade from Lychee 4 to Lychee 5.1, now I'm facing an error message:
Error 500: HttpException Class "Mockery" not found

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Upgrade Lychee files according to https://lycheeorg.github.io/docs/update.html#update-manually
2. Open website
3. See error

**Screenshots**
![image](https://github.com/LycheeOrg/Lychee/assets/6923312/e4e58dfa-3749-466b-ad79-637a10d05e31)

### Output of the diagnostics  [REQUIRED]
_testing.ERROR: Livewire\Features\SupportFileUploads\SupportFileUploads::provide:17 Class "Mockery" not found
Illuminate\Foundation\Http\Kernel::handle:73 Class "Mockery" not found; caused by
testing.ERROR: Carbon\CarbonTimeZone::instance:109 Unknown or bad timezone (UTC+1)
Illuminate\Foundation\Http\Kernel::terminate:77 Unknown or bad timezone (UTC+1); caused by_

### Browser and system
Client: macOS 14.3
PHP: 8.2

**Comment by ildyria** [comment]
> I tried to upgrade from Lychee 4 to Lychee 5.1, now I'm facing an error message:

How did you do this? 
Please do `composer install --no-dev`

**Comment by makorus** [comment]
I tried to do the update like I always did before by downloading the latest zip, unzipping it and overriding my existing files.

When I run the command above, I get the following output:

```
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating optimized autoload files
Warning: Ambiguous class resolution, "Safe\Exceptions\SimplexmlException" was found in both "/example.com/vendor/thecodingmachine/safe/lib/Exceptions/SimplexmlException.php" and "/example.com/vendor/thecodingmachine/safe/generated/Exceptions/SimplexmlException.php", the first will be used.
Warning: Ambiguous class resolution, "Safe\Exceptions\MysqliException" was found in both "/example.com/vendor/thecodingmachine/safe/deprecated/Exceptions/MysqliException.php" and "/example.com/vendor/thecodingmachine/safe/generated/Exceptions/MysqliException.php", the first will be used.
Warning: Ambiguous class resolution, "Safe\Exceptions\PasswordException" was found in both "/example.com/vendor/thecodingmachine/safe/deprecated/Exceptions/PasswordException.php" and "/example.com/vendor/thecodingmachine/safe/generated/Exceptions/PasswordException.php", the first will be used.
Warning: Ambiguous class resolution, "League\Flysystem\Local\FallbackMimeTypeDetector" was found in both "/example.com/vendor/league/flysystem-local/FallbackMimeTypeDetector.php" and "/example.com/vendor/league/flysystem/src/Local/FallbackMimeTypeDetector.php", the first will be used.
Warning: Ambiguous class resolution, "League\Flysystem\Local\LocalFilesystemAdapter" was found in both "/example.com/vendor/league/flysystem-local/LocalFilesystemAdapter.php" and "/example.com/vendor/league/flysystem/src/Local/LocalFilesystemAdapter.php", the first will be used.
Warning: Ambiguous class resolution, "Illuminate\Support\HigherOrderWhenProxy" was found in both "/example.com/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderWhenProxy.php" and "/example.com/vendor/laravel/framework/src/Illuminate/Conditionable/HigherOrderWhenProxy.php", the first will be used.
Warning: Ambiguous class resolution, "Illuminate\Support\Traits\Conditionable" was found in both "/example.com/vendor/laravel/framework/src/Illuminate/Conditionable/Traits/Conditionable.php" and "/example.com/vendor/laravel/framework/src/Illuminate/Support/Traits/Conditionable.php", the first will be used.
Warning: Ambiguous class resolution, "Carbon\Doctrine\CarbonImmutableType" was found in both "/example.com/vendor/carbonphp/carbon-doctrine-types/src/Carbon/Doctrine/CarbonImmutableType.php" and "/example.com/vendor/nesbot/carbon/src/Carbon/Doctrine/CarbonImmutableType.php", the first will be used.
Warning: Ambiguous class resolution, "Carbon\Doctrine\CarbonTypeConverter" was found in both "/example.com/vendor/carbonphp/carbon-doctrine-types/src/Carbon/Doctrine/CarbonTypeConverter.php" and "/example.com/vendor/nesbot/carbon/src/Carbon/Doctrine/CarbonTypeConverter.php", the first will be used.
Warning: Ambiguous class resolution, "Carbon\Doctrine\DateTimeImmutableType" was found in both "/example.com/vendor/carbonphp/carbon-doctrine-types/src/Carbon/Doctrine/DateTimeImmutableType.php" and "/example.com/vendor/nesbot/carbon/src/Carbon/Doctrine/DateTimeImmutableType.php", the first will be used.
Warning: Ambiguous class resolution, "Carbon\Doctrine\DateTimeType" was found in both "/example.com/vendor/carbonphp/carbon-doctrine-types/src/Carbon/Doctrine/DateTimeType.php" and "/example.com/vendor/nesbot/carbon/src/Carbon/Doctrine/DateTimeType.php", the first will be used.
Warning: Ambiguous class resolution, "Carbon\Doctrine\DateTimeDefaultPrecision" was found in both "/example.com/vendor/carbonphp/carbon-doctrine-types/src/Carbon/Doctrine/DateTimeDefaultPrecision.php" and "/example.com/vendor/nesbot/carbon/src/Carbon/Doctrine/DateTimeDefaultPrecision.php", the first will be used.
Warning: Ambiguous class resolution, "Carbon\Doctrine\CarbonDoctrineType" was found in both "/example.com/vendor/carbonphp/carbon-doctrine-types/src/Carbon/Doctrine/CarbonDoctrineType.php" and "/example.com/vendor/nesbot/carbon/src/Carbon/Doctrine/CarbonDoctrineType.php", the first will be used.
Warning: Ambiguous class resolution, "Carbon\Doctrine\CarbonType" was found in both "/example.com/vendor/carbonphp/carbon-doctrine-types/src/Carbon/Doctrine/CarbonType.php" and "/example.com/vendor/nesbot/carbon/src/Carbon/Doctrine/CarbonType.php", the first will be used.
Class Evenement\EventEmitterInterface located in ./vendor/evenement/evenement/src/Evenement/EventEmitterInterface.php does not comply with psr-4 autoloading standard. Skipping.
Class Evenement\EventEmitter located in ./vendor/evenement/evenement/src/Evenement/EventEmitter.php does not comply with psr-4 autoloading standard. Skipping.
Class Evenement\EventEmitterTrait located in ./vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php does not comply with psr-4 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan optimize --clever --dont-confirm=assume-no

In SupportFileUploads.php line 17:
                             
  Class "Mockery" not found  
                             


In CarbonTimeZone.php line 109:
                                   
  Unknown or bad timezone (UTC+1)  
                                   

> @php artisan package:discover

In SupportFileUploads.php line 17:
                             
  Class "Mockery" not found  
                             


In CarbonTimeZone.php line 109:
                                   
  Unknown or bad timezone (UTC+1)  
                                   

> @php scripts/install_files.php

creating file for CSS personalization

creating file for JS personalization

creating default SQLite database

setting up hooks for git pull and git commits

Warning: copy(.git/hooks/pre-commit): Failed to open stream: No such file or directory in /example.com/vendor/thecodingmachine/safe/generated/filesystem.php on line 114

Fatal error: Uncaught Safe\Exceptions\FilesystemException: copy(.git/hooks/pre-commit): Failed to open stream: No such file or directory in /example.com/vendor/thecodingmachine/safe/generated/Exceptions/FilesystemException.php:9
Stack trace:
#0 /example.com/vendor/thecodingmachine/safe/generated/filesystem.php(117): Safe\Exceptions\FilesystemException::createFromPhpError()
#1 /example.com/scripts/install_files.php(24): Safe\copy('scripts/pre-com...', '.git/hooks/pre-...')
#2 {main}
  thrown in /example.com/vendor/thecodingmachine/safe/generated/Exceptions/FilesystemException.php on line 9
Script @php scripts/install_files.php handling the install_files event returned with error code 255
Script @install_files was called via post-autoload-dump
```

**Comment by ildyria** [comment]
> unzipping it and overriding my existing files.

The problem is that is if some files no longer exists in the new version of vendors, then they are still present in your vendor, and composer will still pick them up.

This is also the case for renamed files within Lychee. As described in the documentation, it saying :
> Replace all existing files, excluding public/uploads/, public/dist/user.css and .env (and database/database.sqlite if using SQLite as your database)

**Replace, not overwrite.** Overwrite is a merge as opposed to complete replacement.
