### ISSUE TITLE
"Invalid access rights" for ../storage even with correct permissions, PHP error

### ISSUE THREAD

**Issue by moldimolt** [LycheeOrg/Lychee#670]
### Detailed description of the problem [REQUIRED]
Hello, 

While attempting to setup Lychee with the latest git master, I'm getting this error: 

```
[21-Jul-2020 11:59:01 UTC] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/html/Lychee/storage/framework/views/0b05a54961a648aa4a4076d41826a2c868a195fd.php): failed to open stream: Permission denied in /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:135
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(135): file_put_contents()
#2 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(150): Illuminate\Filesystem\Filesystem->put()
#3 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(51): Illuminate\View\Compilers\BladeCompiler->compile()
#4 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/View/View.php(139): Illuminate\View\Engines\CompilerEngine->get()
#5 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\View\View->getCon in /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 135
```

I have confirmed that `php-fpm` is running as the user and group `nginx`, and `storage` and `bootstrap/cache` folders are owned by nginx and the permissions are 775. The error occurs regardless of whether `vendor` is owned by nginx or not. I googled this error and saw some users had it caused by SELinux so I set SELinux to permissive and restarted as a test, but this did not resolve the issue either; the error remained the same.

```
[akari@loli Lychee]$ ls -l .
total 532
-rwxr-xr-x.  1 akari akari    371 Jul 21 05:46 after.sh
-rwxr-xr-x.  1 akari akari   3857 Jul 21 05:46 aliases
drwxr-xr-x. 14 akari akari   4096 Jul 21 05:46 app
-rwxr-xr-x.  1 akari akari   1686 Jul 21 05:46 artisan
-rwxr-xr-x.  1 akari akari  42796 Jul 21 05:46 Banner.png
drwxr-xr-x.  3 akari akari     79 Jul 21 05:46 bootstrap
-rwxr-xr-x.  1 akari akari  50882 Jul 21 05:46 codecov.sh
-rwxr-xr-x.  1 akari akari   1218 Jul 21 05:46 codecov.yml
drwxr-xr-x.  2 akari akari     24 Jul 21 05:46 composer-cache
-rwxr-xr-x.  1 akari akari   2596 Jul 21 05:46 composer.json
-rwxr-xr-x.  1 akari akari 331192 Jul 21 05:46 composer.lock
drwxr-xr-x.  2 akari akari   4096 Jul 21 08:19 config
drwxr-xr-x.  5 akari akari     95 Jul 21 05:47 database
-rwxr-xr-x.  1 akari akari   3231 Jul 21 05:46 gen_release
-rwxr-xr-x.  1 akari akari     97 Jul 21 05:46 index.php
-rwxr-xr-x.  1 akari akari    731 Jul 21 05:46 install_files.sh
-rwxr-xr-x.  1 akari akari   1118 Jul 21 05:46 LICENSE
-rwxr-xr-x.  1 akari akari   3927 Jul 21 05:46 makefile
-rwxr-xr-x.  1 akari akari   1022 Jul 21 05:46 package.json
-rwxr-xr-x.  1 akari akari   1330 Jul 21 05:46 phpunit.xml
-rwxr-xr-x.  1 akari akari    935 Jul 21 05:46 post-merge
-rwxr-xr-x.  1 akari akari    574 Jul 21 05:46 pre-commit
drwxr-xr-x.  9 akari akari    209 Jul 21 08:00 public
-rwxr-xr-x.  1 akari akari   5709 Jul 21 05:46 readme.md
drwxr-xr-x.  5 akari akari     45 Jul 21 05:46 resources
drwxr-xr-x.  2 akari akari    111 Jul 21 05:46 routes
-rwxr-xr-x.  1 akari akari    732 Jul 21 05:46 SECURITY.md
-rwxr-xr-x.  1 akari akari    563 Jul 21 05:46 server.php
-rwxr-xr-x.  1 akari akari    223 Jul 21 05:46 setup_exiftool.sh
-rwxr-xr-x.  1 akari akari   1965 Jul 21 05:46 simple_error_template.html
drwxrwxr-x.  6 akari nginx     62 Jul 21 05:46 storage
-rwxr-xr-x.  1 akari akari    294 Jul 21 05:46 test_dev.sh
-rwxr-xr-x.  1 akari akari    174 Jul 21 05:46 test_dist.sh
drwxr-xr-x.  3 akari akari     71 Jul 21 05:46 tests
-rwxr-xr-x.  1 akari akari   1705 Jul 21 05:46 Vagrantfile
drwxrwxr-x. 40 akari akari   4096 Jul 21 05:47 vendor
-rwxr-xr-x.  1 akari akari      5 Jul 21 05:46 version.md
-rwxr-xr-x.  1 akari akari    549 Jul 21 05:46 webpack.mix.js
```
```
[akari@loli Lychee]$ ls -l storage
total 0
drwxrwxr-x. 3 akari nginx 38 Jul 21 05:46 app
drwxrwxr-x. 2 akari nginx 24 Jul 21 05:46 debugbar
drwxrwxr-x. 6 akari nginx 81 Jul 21 05:46 framework
drwxrwxr-x. 2 akari nginx 43 Jul 21 06:37 logs
```
```
[akari@loli Lychee]$ ls -l bootstrap/cache
total 20
-rwxrwxr-x. 1 akari nginx  1006 Jul 21 05:47 packages.php
-rwxrwxr-x. 1 akari nginx 13710 Jul 21 05:47 services.php
```
```
/etc/php-fpm.d/www.conf snippet
; Start a new pool named 'www'.
; the variable $pool can be used in any directive and will be replaced by the
; pool name ('www' here)
[www]

...

; Unix user/group of processes
; Note: The user is mandatory. If the group is not set, the default user's group
;       will be used.
; RPM: apache user chosen to provide access to the same directories as httpd
user = nginx
; RPM: Keep a group allowed to write in log dir.
group = nginx

; The address on which to accept FastCGI requests.
; Valid syntaxes are:
;   'ip.add.re.ss:port'    - to listen on a TCP socket to a specific IPv4 address on
;                            a specific port;
;   '[ip:6:addr:ess]:port' - to listen on a TCP socket to a specific IPv6 address on
;                            a specific port;
;   'port'                 - to listen on a TCP socket to all addresses
;                            (IPv6 and IPv4-mapped) on a specific port;
;   '/path/to/unix/socket' - to listen on a unix socket.
; Note: This value is mandatory.
listen = /run/php-fpm/www.sock
```

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*
```
Diagnostics
-----------
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
Warning: Pictures that are rotated lose their metadata! Please enable Imagick in settings to avoid that.
Error: username not set in database
Error: password not set in database
Error: sorting_Photos not set in database
Error: sorting_Albums not set in database
Error: imagick not set in database
Error: skip_duplicates not set in database
Error: check_for_updates not set in database
Error: version not set in database
Error: SQLSTATE[HY000] [2002] No such file or directory (SQL: select `key`, `value`, `type_range` from `configs`)
Warning: Dropbox import not working. No property for dropbox_key.

System Information
------------------
Lychee Version (git):            master (febbad3) - Data not in Cache
DB Version:                      4.0.0

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       false

System:                          Linux
PHP Version:                     7.4
Max uploaded file size:          2M
Max post size:                   8M
Unknown SQL Version:             unknown

Imagick:                         1
Imagick Active:                  key not found in settings
Imagick Version:                 1691
GD Version:                      2.3.0

Config Information
------------------
Error: SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from `configs` where `confidentiality` <= 2 order by `id` asc)
```

### Browser and system
**Server info:**
```
Operating System: Fedora 32 (Server Edition)
CPE OS Name: cpe:/o:fedoraproject:fedora:32
Kernel: Linux 5.7.9-200.fc32.x86_64
Architecture: x86-64
```
**Browser/system attempting to access server:**
```
Microsoft Edge | 85.0.564.8 (Official build) dev (64-bit)
Revision | 60f289a8c53d09286d89d82f64cfe644fbfb4afe
Operating system | Windows 10 OS Version 2004 (Build 20170.1000)
```

**Comment by ildyria** [comment]
What about the rights of the folder `views` in framework ?

**Comment by moldimolt** [comment]
Inside `/var/www/html/Lychee/vendor/laravel/framework`? If so, there is no folder called `views`:

```
[akari@loli framework]$ ls -l
total 16
-rwxrwxr-x. 1 akari akari 6412 Jul 14 09:42 composer.json
-rwxrwxr-x. 1 akari akari 1075 Jul 14 09:42 LICENSE.md
-rwxrwxr-x. 1 akari akari 3318 Jul 14 09:42 README.md
drwxrwxr-x. 3 akari akari   24 Jul 14 09:42 src
```

**Comment by ildyria** [comment]
The vendor folder is not interfering here:
```
file_put_contents(/var/www/html/Lychee/storage/framework/views/0b05a54961a648aa4a4076d41826a2c868a195fd.php): failed to open stream
```
Basically anything in `storage` need writing access (recursively).

**Comment by moldimolt** [comment]
Ah, apologies, I misunderstood the folder you meant, the permissions are set correctly on `storage/framework/views` I believe:

```
[akari@loli framework]$ ls -l
total 0
drwxrwxr-x. 3 akari nginx 36 Jul 21 05:46 cache
drwxrwxr-x. 2 akari nginx 24 Jul 21 05:46 sessions
drwxrwxr-x. 2 akari nginx 24 Jul 21 05:46 testing
drwxrwxr-x. 2 akari nginx 24 Jul 21 05:46 views
```
```
[akari@loli framework]$ ls -l ..
total 0
drwxrwxr-x. 3 akari nginx 38 Jul 21 05:46 app
drwxrwxr-x. 2 akari nginx 24 Jul 21 05:46 debugbar
drwxrwxr-x. 6 akari nginx 81 Jul 21 05:46 framework
drwxrwxr-x. 2 akari nginx 43 Jul 21 06:37 logs
```

**Comment by ildyria** [comment]
Then, there may be a file named `0b05a54961a648aa4a4076d41826a2c868a195fd.php` in `storage/framework/views`, try to remove it and refresh.

If you get a error about `laravel.log` in `storage/logs`, you just need to make sure that the file has the correct access right too.

**Comment by moldimolt** [comment]
Unfortunately, `views` is entirely empty: 

```
[akari@loli views]$ ls -l
total 0
``` 
```
[akari@loli views]$ ls -l ../../logs
total 4
-rwxrwxr-x. 1 akari nginx 2928 Jul 21 06:37 laravel.log
```

**Comment by ildyria** [comment]
Have you had a look at this too: https://stackoverflow.com/a/37258323/3981163 ?

**Comment by ildyria** [comment]
Honestly, I can't really help you more than that; maybe @d7415 can give it a jab.

From my point of view this is a server side configuration problem, not a Lychee bug. :(

**Comment by moldimolt** [comment]
Thank you. I had tried setting SELinux to Permissive already just to see if it was SELinux getting in the way and that did not resolve the issue, but for some reason `chcon -R -t httpd_sys_rw_content_t storage` did. I guess Fedora Server must have overly restrictive SELinux rules, as I didn't have this issue with Ubuntu 20.04.

**Comment by ildyria** [comment]
I can already foresee that you will most likely have to do the same for the folder `public/uploads`...

**Comment by moldimolt** [comment]
I got Lychee working fully and these were my final results:

With Lychee running on Fedora 32 Server, you *must* run 

```
chcon -R -t httpd_sys_rw_content_t storage
chcon -R -t httpd_sys_rw_content_t bootstrap/cache
chcon -R -t httpd_sys_rw_content_t public/uploads
chcon -R -t httpd_sys_rw_content_t public/dist
``` 

If you don't, even with the correct user/group ownership and permissions, SELinux will stop the nginx user from accessing these folders, breaking Lychee.

**Comment by ildyria** [comment]
Can you make a PR on https://github.com/LycheeOrg/Lycheeorg.github.io , specifically modifying that file : https://github.com/LycheeOrg/LycheeOrg.github.io/blob/master/docs/md/faq.md with your findings ? :+1: 

This will update: https://lycheeorg.github.io/docs/faq.html :)

**Comment by moldimolt** [comment]
Will do.

**Comment by moldimolt** [comment]
[Completed](https://github.com/LycheeOrg/LycheeOrg.github.io/pull/20).
