### ISSUE TITLE
Docker error in creating storage folder

### ISSUE THREAD

**Issue by rightsaidfred99** [LycheeOrg/Lychee#795]
### Detailed description of the problem [REQUIRED]
I've never submitted a bug before so hope I'm doing the right thing. 
When creating a docker setup with mariaDb on a Synology Docker container, everything works well but for some reason Lychee cannot create the "Storage" folder in amongst all the other folders. 

It'll just create all the other files and folders and thus I connect as a 500 error

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. spawn docker instance
2. it'll create all the files and folders but lock up on "storage"

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*
There is no existing directory at "/app/lychee/storage/logs" and it could not be created: File exists
UnexpectedValueException
in /app/lychee/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php (line 172)
in /app/lychee/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php -> createDir (line 100)
in /app/lychee/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php -> write (line 42)
in /app/lychee/vendor/monolog/monolog/src/Monolog/Logger.php -> handle (line 325)
in /app/lychee/vendor/monolog/monolog/src/Monolog/Logger.php -> addRecord (line 543)
in /app/lychee/vendor/laravel/framework/src/Illuminate/Log/Logger.php -> error (line 174)
in /app/lychee/vendor/laravel/framework/src/Illuminate/Log/Logger.php -> writeLog (line 87)
in /app/lychee/vendor/laravel/framework/src/Illuminate/Log/LogManager.php -> error (line 547)
in /app/lychee/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php -> error (line 237)
Handler->report(object(UnexpectedValueException))
in /app/lychee/app/Exceptions/Handler.php (line 46)
     * @throws Throwable     */    public function report(Throwable $exception)    {        // @codeCoverageIgnoreStart        parent::report($exception);        // @codeCoverageIgnoreEnd    }    /**     * Render an exception into an HTTP response.
in /app/lychee/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php -> report (line 88)
HandleExceptions->handleException(object(UnexpectedValueException))
### Stack Trace

UnexpectedValueException:
There is no existing directory at "/app/lychee/storage/logs" and it could not be created: File exists

  at /app/lychee/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:172
  at Monolog\Handler\StreamHandler->createDir()
     (/app/lychee/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:100)
  at Monolog\Handler\StreamHandler->write(array('message' => 'There is no existing directory at "/app/lychee/storage/logs" and it could not be created: File exists', 'context' => array('exception' => object(UnexpectedValueException)), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'production', 'datetime' => object(DateTimeImmutable), 'extra' => array(), 'formatted' => '[2020-11-20 23:20:49] production.ERROR: There is no existing directory at "/app/lychee/storage/logs" and it could not be created: File exists {"exception":"[object] (UnexpectedValueException(code: 0): There is no existing directory at \\"/app/lychee/storage/logs\\" and it could not be created: File exists at /app/lychee/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:172)[stacktrace]#0 /app/lychee/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(100): Monolog\\\\Handler\\\\StreamHandler->createDir()#1 /app/lychee/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(42): Monolog\\\\Handler\\\\StreamHandler->write(Array)#2 /app/lychee/vendor/monolog/monolog/src/Monolog/Logger.php(325): Monolog\\\\Handler\\\\AbstractProcessingHandler->handle(Array)#3 /app/lychee/vendor/monolog/monolog/src/Monolog/Logger.php(543): Monolog\\\\Logger->addRecord(400, \'Please provide ...\', Array)#4 /app/lychee/vendor/laravel/framework/src/Illuminate/Log/Logger.php(174): Monolog\\\\Logger->error(\'Please provide ...\', Array)#5 /app/lychee/vendor/laravel/framework/src/Illuminate/Log/Logger.php(87): Illuminate\\\\Log\\\\Logger->writeLog(\'error\', \'Please provide ...\', Array)#6 /app/lychee/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(547): Illuminate\\\\Log\\\\Logger->error(\'Please provide ...\', Array)#7 /app/lychee/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(237): Illuminate\\\\Log\\\\LogManager->error(\'Please provide ...\', Array)#8 /app/lychee/app/Exceptions/Handler.php(46): Illuminate\\\\Foundation\\\\Exceptions\\\\Handler->report(Object(InvalidArgumentException))#9 /app/lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(404): App\\\\Exceptions\\\\Handler->report(Object(InvalidArgumentException))#10 /app/lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(112): Illuminate\\\\Foundation\\\\Http\\\\Kernel->reportException(Object(InvalidArgumentException))#11 /app/lychee/public/index.php(74): Illuminate\\\\Foundation\\\\Http\\\\Kernel->handle(Object(Illuminate\\\\Http\\\\Request))#12 {main}"} '))
     (/app/lychee/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:42)
  at Monolog\Handler\AbstractProcessingHandler->handle(array('message' => 'There is no existing directory at "/app/lychee/storage/logs" and it could not be created: File exists', 'context' => array('exception' => object(UnexpectedValueException)), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'production', 'datetime' => object(DateTimeImmutable), 'extra' => array(), 'formatted' => '[2020-11-20 23:20:49] production.ERROR: There is no existing directory at "/app/lychee/storage/logs" and it could not be created: File exists {"exception":"[object] (UnexpectedValueException(code: 0): There is no existing directory at \\"/app/lychee/storage/logs\\" and it could not be created: File exists at /app/lychee/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:172)[stacktrace]#0 /app/lychee/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(100): Monolog\\\\Handler\\\\StreamHandler->createDir()#1 /app/lychee/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(42): Monolog\\\\Handler\\\\StreamHandler->write(Array)#2 /app/lychee/vendor/monolog/monolog/src/Monolog/Logger.php(325): Monolog\\\\Handler\\\\AbstractProcessingHandler->handle(Array)#3 /app/lychee/vendor/monolog/monolog/src/Monolog/Logger.php(543): Monolog\\\\Logger->addRecord(400, \'Please provide ...\', Array)#4 /app/lychee/vendor/laravel/framework/src/Illuminate/Log/Logger.php(174): Monolog\\\\Logger->error(\'Please provide ...\', Array)#5 /app/lychee/vendor/laravel/framework/src/Illuminate/Log/Logger.php(87): Illuminate\\\\Log\\\\Logger->writeLog(\'error\', \'Please provide ...\', Array)#6 /app/lychee/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(547): Illuminate\\\\Log\\\\Logger->error(\'Please provide ...\', Array)#7 /app/lychee/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(237): Illuminate\\\\Log\\\\LogManager->error(\'Please provide ...\', Array)#8 /app/lychee/app/Exceptions/Handler.php(46): Illuminate\\\\Foundation\\\\Exceptions\\\\Handler->report(Object(InvalidArgumentException))#9 /app/lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(404): App\\\\Exceptions\\\\Handler->report(Object(InvalidArgumentException))#10 /app/lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(112): Illuminate\\\\Foundation\\\\Http\\\\Kernel->reportException(Object(InvalidArgumentException))#11 /app/lychee/public/index.php(74): Illuminate\\\\Foundation\\\\Http\\\\Kernel->handle(Object(Illuminate\\\\Http\\\\Request))#12 {main}"} '))
     (/app/lychee/vendor/monolog/monolog/src/Monolog/Logger.php:325)
  at Monolog\Logger->addRecord(400, 'There is no existing directory at "/app/lychee/storage/logs" and it could not be created: File exists', array('exception' => object(UnexpectedValueException)))
     (/app/lychee/vendor/monolog/monolog/src/Monolog/Logger.php:543)
  at Monolog\Logger->error('There is no existing directory at "/app/lychee/storage/logs" and it could not be created: File exists', array('exception' => object(UnexpectedValueException)))
     (/app/lychee/vendor/laravel/framework/src/Illuminate/Log/Logger.php:174)
  at Illuminate\Log\Logger->writeLog('error', 'There is no existing directory at "/app/lychee/storage/logs" and it could not be created: File exists', array('exception' => object(UnexpectedValueException)))
     (/app/lychee/vendor/laravel/framework/src/Illuminate/Log/Logger.php:87)
  at Illuminate\Log\Logger->error('There is no existing directory at "/app/lychee/storage/logs" and it could not be created: File exists', array('exception' => object(UnexpectedValueException)))
     (/app/lychee/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:547)
  at Illuminate\Log\LogManager->error('There is no existing directory at "/app/lychee/storage/logs" and it could not be created: File exists', array('exception' => object(UnexpectedValueException)))
     (/app/lychee/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:237)
  at Illuminate\Foundation\Exceptions\Handler->report(object(UnexpectedValueException))
     (/app/lychee/app/Exceptions/Handler.php:46)
  at App\Exceptions\Handler->report(object(UnexpectedValueException))
     (/app/lychee/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:88)
  at Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(object(UnexpectedValueException))

**Comment by d7415** [comment]
That doesn't look like our image. Where are you getting the image from?

**Comment by rightsaidfred99** [comment]
Ah, that might be something. It's the linuxserver build I guess. 

Perhaps it's better to use the official one instead of a 3rd party. I shall try

**Comment by d7415** [comment]
Theirs should work, but you'd have to ask them for support.
