### ISSUE TITLE
command line sync fails

### ISSUE THREAD

**Issue by evoludolab** [LycheeOrg/Lychee#825]
### Detailed description of the problem [REQUIRED]
Trying to import photos on the command line with
`php artisan lychee:sync`
fails with the following error:
`Request Session data while not being logged in.`
The full output is
```
prompt> php artisan lychee:sync /path/to/images
Start syncing.
Status: /path/to/images: 0%
App\Exceptions\NotLoggedInException: Request Session data while not being logged in. in /<snip>/Lychee/app/ModelFunctions/SessionFunctions.php:64
Stack trace:
#0 /<snip>/Lychee/app/ModelFunctions/PhotoFunctions.php(353): App\ModelFunctions\SessionFunctions->id()
#1 /<snip>/Lychee/app/Http/Controllers/ImportController.php(81): App\ModelFunctions\PhotoFunctions->add()
#2 /<snip>/Lychee/app/Http/Controllers/ImportController.php(371): App\Http\Controllers\ImportController->photo()
#3 /<snip>/Lychee/app/Console/Commands/Sync.php(65): App\Http\Controllers\ImportController->server_exec()
#4 /<snip>/Lychee/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\Sync->handle()
#5 /<snip>/Lychee/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /<snip>/Lychee/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#7 /<snip>/Lychee/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#8 /<snip>/Lychee/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\Container\BoundMethod::call()
#9 /<snip>/Lychee/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#10 /<snip>/Lychee/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute()
#11 /<snip>/Lychee/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#12 /<snip>/Lychee/vendor/symfony/console/Application.php(971): Illuminate\Console\Command->run()
#13 /<snip>/Lychee/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#14 /<snip>/Lychee/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
#15 /<snip>/Lychee/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#16 /<snip>/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#17 /<snip>/Lychee/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#18 {main}
Done syncing. 
```
This issue had been reported in #646. Possibly this is a regression. In case it matters, this is a fresh install from github and an attempt to do an initial import.

### Output of the diagnostics  [REQUIRED]
output of `php artisan lychee:diagnostics`:
```
prompt> php artisan lychee:diagnostics
Diagnostics
-----------
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
Warning: Dropbox import not working. dropbox_key is empty.

System Information
------------------
Lychee Version (git):            master (0523768) - Data not in Cache
DB Version:                      4.0.9

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       false

System:                          Darwin
PHP Version:                     7.4
Max uploaded file size:          200M
Max post size:                   100M
SQLite Version:                  3.34.0

Imagick:                         1
Imagick Active:                  1
Imagick Version:                 1691
GD Version:                      bundled (2.1.0 compatible)

Config Information
------------------
version:                         040009
check_for_updates:               0
sorting_Photos_col:              title
sorting_Photos_order:            ASC
sorting_Albums_col:              title
sorting_Albums_order:            ASC
imagick:                         1
skip_duplicates:                 0
small_max_width:                 0
small_max_height:                360
medium_max_width:                1920
medium_max_height:               1080
lang:                            en
layout:                          1
image_overlay:                   1
image_overlay_type:              desc
default_license:                 none
compression_quality:             90
full_photo:                      1
delete_imported:                 0
Mod_Frame:                       1
Mod_Frame_refresh:               30
thumb_2x:                        1
small_2x:                        1
medium_2x:                       0
landing_page_enable:             0
landing_owner:                   John Smith
landing_title:                   John Smith
landing_subtitle:                Cats, Dogs & Humans Photography
landing_facebook:                https://www.facebook.com/JohnSmith
landing_flickr:                  https://www.flickr.com/JohnSmith
landing_twitter:                 https://www.twitter.com/JohnSmith
landing_instagram:               https://instagram.com/JohnSmith
landing_youtube:                 https://www.youtube.com/JohnSmith
landing_background:              dist/cat.jpg
site_title:                      Lychee v4
site_copyright_enable:           1
site_copyright_begin:            2020
site_copyright_end:              2020
additional_footer_text:          
display_social_in_gallery:       0
public_search:                   0
SL_enable:                       0
SL_for_admin:                    0
public_recent:                   0
recent_age:                      1
public_starred:                  0
downloadable:                    0
photos_wraparound:               1
map_display:                     1
zip64:                           1
map_display_public:              0
map_provider:                    Wikimedia
force_32bit_ids:                 0
map_include_subalbums:           0
update_check_every_days:         3
has_exiftool:                    1
share_button_visible:            0
import_via_symlink:              1
has_ffmpeg:                      1
location_decoding:               0
location_decoding_timeout:       30
location_show:                   1
location_show_public:            0
rss_enable:                      0
rss_recent_days:                 7
rss_max_items:                   100
prefer_available_xmp_metadata:   0
editor_enabled:                  1
lossless_optimization:           0
swipe_tolerance_x:               150
swipe_tolerance_y:               250
local_takestamp_video_formats:   .avi|.mov
log_max_num_line:                1000
unlock_password_photos_with_url_param: 0
```

### Browser and system
macOS 10.15.7 (command-line issue, independent of browser)

**Comment by ildyria** [comment]
Thank you for your report, this will be fix shortly.

**Comment by ildyria** [comment]
Fixed.
