### ISSUE TITLE
Latest release broken? Composer.lock not updated?

### ISSUE THREAD

**Issue by r7l** [LycheeOrg/Lychee#838]
After updating to 4.1.0, composer starts to complain about the lock file not being up to date:

`Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run 'composer update' or 'composer update <package name>'.`

Looking at the most recent commits, it does in fact seems as if composer.lock is 2 days older then composer.json.

It still installs packages but starting Lychee is causing a blank page with error messages in laravel.log:

`2020-12-28 15:17:19] production.ERROR: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' {"exception":"[object] (ParseError(code: 0): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' at ...`

It all went away after running `composer update` but i don't think it should be this way.

**Comment by ildyria** [comment]
Weird.

**Comment by ildyria** [comment]
> It still installs packages but starting Lychee is causing a blank page with error messages in laravel.log:
> 
> `2020-12-28 15:17:19] production.ERROR: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' {"exception":"[object] (ParseError(code: 0): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' at ...`
> 
> It all went away after running `composer update` but i don't think it should be this way.

I just tested on my end, while I do get the warning, I surprisingly do not have the mentioned error.

**Comment by ildyria** [comment]
I'm not worried about the composer.lock not being up to date. But that:
```
2020-12-28 15:17:19] production.ERROR: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' {"exception":"[object] (ParseError(code: 0): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' at ...
```
is more worrisome. Could you provide more details ? :|

**Comment by r7l** [comment]
The error went away for me after running `composer update`.

Not sure what exactly caused it for me. I was updating from a working 4.0.8 to 4.1.0 and also did the database update command on CLI as it was showing this new update page. It all went through ok up until i've reopened the site. This is when i got this error. But it also went away after running the composer update. It is running fine now without any issues.

I am not sure how to get this error back without reinstalling the older version of the site (4.0.8) with a backup from last week and redoing the entire process.

**Comment by ildyria** [comment]
but you said the error is in your laravel.log so you should still have the logs about it. :)

**Comment by r7l** [comment]
This is the error message:

```
[2020-12-28 15:18:49] production.ERROR: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' {"exception":"[object] (ParseError(code: 0): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' at /srv/http/public/htdocs/app/ModelFunctions/AlbumFunctions.php:223)
[stacktrace]
#0 /srv/http/public/htdocs/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/srv/http/publi...')
#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\ModelFuncti...')
#2 [internal function]: spl_autoload_call('App\\\\ModelFuncti...')
#3 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Container/Container.php(830): ReflectionClass->__construct('App\\\\ModelFuncti...')
#4 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Container/Container.php(279): Illuminate\\Container\\Container->build('App\\\\ModelFuncti...')
#5 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Container/Container.php(826): Illuminate\\Container\\Container->Illuminate\\Container\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#6 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Container/Container.php(712): Illuminate\\Container\\Container->build(Object(Closure))
#7 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve('App\\\\ModelFuncti...', Array, true)
#8 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Foundation\\Application->resolve('App\\\\ModelFuncti...', Array)
#9 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make('App\\\\ModelFuncti...', Array)
#10 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Container/Container.php(980): Illuminate\\Foundation\\Application->make('App\\\\ModelFuncti...')
#11 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Container/Container.php(900): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#12 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Container/Container.php(861): Illuminate\\Container\\Container->resolveDependencies(Array)
#13 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Container/Container.php(712): Illuminate\\Container\\Container->build('App\\\\Http\\\\Contro...')
#14 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Contro...', Array, true)
#15 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Foundation\\Application->resolve('App\\\\Http\\\\Contro...', Array)
#16 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make('App\\\\Http\\\\Contro...', Array)
#17 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(268): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Contro...')
#18 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(989): Illuminate\\Routing\\Route->getController()
#19 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(950): Illuminate\\Routing\\Route->controllerMiddleware()
#20 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(709): Illuminate\\Routing\\Route->gatherMiddleware()
#21 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Router->gatherRouteMiddleware(Object(Illuminate\\Routing\\Route))
#22 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#23 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#24 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#25 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#26 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#27 /srv/http/public/htdocs/vendor/bepsvpt/secure-headers/src/SecureHeadersMiddleware.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Bepsvpt\\SecureHeaders\\SecureHeadersMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /srv/http/public/htdocs/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#41 /srv/http/public/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#42 /srv/http/public/htdocs/public/index.php(74): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#43 {main}
"} 
```

When thinking about this issue, it might actually been my fault for the error above because i had PHP 7.3 running when starting the update. But i was confused from composer as it did only complain about the the state of composer.lock and instead of breaking it simply went through. It only started complaining about the PHP version when trying to run `composer update`.

So instead of digging deeper into the issue, i was just updating PHP to be able to get on with composer, as i thought this error to be caused by some broken dependency. So the update of PHP might have caused the error to go away, while the state of composer.lock file might not have been the greater cause of issues but instead just confusing me and leading me to a different direction.

**Comment by ildyria** [comment]
Yes. This is an error due to PHP 7.3 :)

See here: https://github.com/LycheeOrg/Lychee/commit/bd13c41ed2da713efef1a8783184749cbd43fa35#diff-3327910db3c0a08c34fed7ade9a330fb99652f208827a024d3b343f40aad1a7b from https://github.com/LycheeOrg/Lychee/pull/799

**Comment by ildyria** [comment]
I'm closing as this is not an issue. :) Still thank you for reporting it. :+1:
