### ISSUE TITLE
Error while syncing from command line

### ISSUE THREAD

**Issue by Nykri** [LycheeOrg/Lychee#841]
### Detailed description of the problem [REQUIRED]
*I was syncing a folder in command line when I got an error that I can't understand. I tried again and got the same error at the same percentage of completion of folder. It's probably happening on the same image but the error doesn't give any information on which one it is.*

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Execute `sudo php /media/data/lychee/artisan lychee:sync /photo_folder --resync_metadata --owner_id=2`

**Screenshots**
```
ErrorException: getimagesize(): Read error! in /media/data/lychee/vendor/lychee-org/php-exif/lib/PHPExif/Adapter/Native.php:209                                                                                 
Stack trace:                                                                                            
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'getimagesize():...', '/media/data/lyc...', 209, Array)                                                                
#1 /media/data/lychee/vendor/lychee-org/php-exif/lib/PHPExif/Adapter/Native.php(209): getimagesize('/var/www/lychee...')
#2 /media/data/lychee/vendor/lychee-org/php-exif/lib/PHPExif/Reader/Reader.php(108): PHPExif\Adapter\Native->getExifFromFile('/var/www/lychee...')
#3 /media/data/lychee/app/Metadata/Extractor.php(120): PHPExif\Reader\Reader->read('/var/www/lychee...')
#4 /media/data/lychee/app/ModelFunctions/PhotoFunctions.php(926): App\Metadata\Extractor->extract('/var/www/lychee...', 'photo')
#5 /media/data/lychee/app/ModelFunctions/PhotoFunctions.php(284): App\ModelFunctions\PhotoFunctions->getFileMetadata(Array, '/var/www/lychee...', 'photo', '.JPG')
#6 /media/data/lychee/app/Http/Controllers/ImportController.php(81): App\ModelFunctions\PhotoFunctions->add(Array, 1609200564, false, true, true)
#7 /media/data/lychee/app/Http/Controllers/ImportController.php(371): App\Http\Controllers\ImportController->photo('/media/data/Pho...', false, 1609200564, true, true)
#8 /media/data/lychee/app/Http/Controllers/ImportController.php(407): App\Http\Controllers\ImportController->server_exec('/media/data/Pho...', 1609200564, false, true, NULL, true)
#9 /media/data/lychee/app/Console/Commands/Sync.php(60): App\Http\Controllers\ImportController->server_exec('/media/data/Pho...', 0, false, true, NULL, true)
#10 [internal function]: App\Console\Commands\Sync->handle()
#11 /media/data/lychee/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array(Array, Array)
#12 /media/data/lychee/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#13 /media/data/lychee/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#14 /media/data/lychee/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#15 /media/data/lychee/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#16 /media/data/lychee/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call(Array)
#17 /media/data/lychee/vendor/symfony/console/Command/Command.php(258): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#18 /media/data/lychee/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#19 /media/data/lychee/vendor/symfony/console/Application.php(916): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /media/data/lychee/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\Sync), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /media/data/lychee/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /media/data/lychee/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /media/data/lychee/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /media/data/lychee/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 {main}
```

### Output of the diagnostics  [REQUIRED]
```
Diagnostics
    -------
    Info: Latest version of PHP is 7.4
    Warning: Using 32 bit PHP, recommended upgrade to 64 bit
    Warning: Dropbox import not working. dropbox_key is empty.



    System Information
    --------------
    Lychee Version (release):        4.0.8
    DB Version:                      4.0.8
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.3
    Max uploaded file size:          512M
    Max post size:                   512M
    MySQL Version:                   10.3.23-MariaDB-0+deb10u1
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1690
    GD Version:                      2.2.5
```

### Browser and system
Raspbian

**Comment by ildyria** [comment]
Most likely fixed (see here: https://github.com/LycheeOrg/Lychee/pull/826/files).
Please update to version 4.1.0.

I'm closing this. Feel free to re-open if this is still broken after updating.
